//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using RTS;
public class OilPump : Building {


		public float rechargeTime = 5.0f;
		private float currentChargeTime = 0f;

	protected override void Update () {
		base.Update ();
		
		currentChargeTime += Time.deltaTime;
		if (player) {
			gainMoney ();
		}
	}

	protected virtual void gainMoney() {
		if (!needsBuilding) {
			if (currentChargeTime >= rechargeTime) {
				//if(audioElement != null && Time.timeScale > 0) audioElement.Play(gainMoneySound);
				currentChargeTime = 0.0f;
				player.AddResource (ResourceType.Money, 50);
			}
		}
	}
}

