//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using RTS;
public class PowerPlant : Building {
	bool powerSupplied;

	protected override void Start ()
	{
		base.Start ();
		powerSupplied = false;
	}

	protected override void Update(){
		if (player) {
			if (!powerSupplied && (!needsBuilding)) {
				gainPower ();
				powerSupplied = true;
			}
		}
	}

	protected virtual void gainPower() {
		if (!powerSupplied&&!needsBuilding&&player.name!=null) {
			player.AddResource (ResourceType.Power, 50);
		}
	}
	protected void OnDestroy(){
		if (player) {
			player.AddResource (ResourceType.Power, -50);
		}
	}
}

