//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using RTS;
public class PowerPlant : Building {

	protected override void Start ()
	{
		base.Start ();
		gainPower ();
	}
	protected virtual void gainPower() {
		if (!needsBuilding) {
			player.AddResource (ResourceType.Power, 50);
		}
	}
	protected void OnDestroy(){
		player.AddResource (ResourceType.Power, -50);
	}
}

